version: '3.8'
services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb1

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  spring-introductory-project:
    build:
      context: ./spring-introductory-project
      dockerfile: Dockerfile
    container_name: backend-spring
    ports:
       - "8080:8080"
    
    tty: true