version: '3.10'
services:
  db:
    image: postgres:15.3-bookworm
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb1
      - TZ=Europe/Warsaw

    volumes:
      - ./postgres-data:/app/postgresql/data

  spring-introductory-project:
    build:
      context: ./spring-introductory-project
      dockerfile: Dockerfile
    container_name: backend-spring
    ports:
       - "8080:8080"
       - "35729:35729"
       - "5005:5005"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - TZ=Europe/Warsaw
    volumes:
      - ./spring-introductory-project/src/main:/app/spring-introductory-project/src/main/
      - ./spring-introductory-project/src/test/:/app/spring-introductory-project/src/test/
      - ./spring-introductory-project/target/:/app/spring-introductory-project/target/
